name: Download File

permissions:
  contents: read

on:
  workflow_dispatch:

jobs:
  downloader:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download the file
        run: |
          wget "https://cdimage.ubuntu.com/kubuntu/releases/25.10/release/kubuntu-25.10-desktop-amd64.iso" -O downloaded.bin

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Download-file
          path: downloaded.bin
